name: Preview deploy

on:
  pull_request:
    types:
      - synchronize
      - opened
env:
  GCLOUD_PROJECT_DEV: "croct-dev"

jobs:
  deploy-preview:
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rlespinasse/github-slug-action@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: "https://npm.pkg.github.com"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}

      - name: Install dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: npm ci

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "${{ secrets.GCLOUD_WORKLOAD_IDENTITY }}"
          service_account: "${{ secrets.GCLOUD_SERVICE_ACCOUNT }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Enable components
        run: |-
          gcloud auth configure-docker
          gcloud --quiet components install beta

      - name: Build & Publish
        run: |
          sed -i -e "s~http://localhost:6008~https://preview.template-ui-web.croct.dev/pr-${{ github.event.number }}~" .storybook/react/main.ts
          npm run build-storybook -- --quiet --config-dir .storybook/web --output-dir storybook-static/web/pr-${{ github.event.number }}
          npm run build-storybook -- --quiet --config-dir .storybook/react --output-dir storybook-static/react/pr-${{ github.event.number }}

          docker buildx build ./storybook-static/web \
          --file ./Dockerfile \
          --tag gcr.io/${{ env.GCLOUD_PROJECT_DEV }}/storybook-web:${{ env.GITHUB_REF_SLUG_URL }} \
          --push

          docker buildx build ./storybook-static/react \
          --file ./Dockerfile \
          --tag gcr.io/${{ env.GCLOUD_PROJECT_DEV }}/storybook-react:${{ env.GITHUB_REF_SLUG_URL }} \
          --push

      - name: Deploy
        run: |-
          IMAGE_TAG_WEB=gcr.io/${{ env.GCLOUD_PROJECT_DEV }}/storybook-web:${{ env.GITHUB_REF_SLUG_URL }}
          IMAGE_TAG_REACT=gcr.io/${{ env.GCLOUD_PROJECT_DEV }}/storybook-react:${{ env.GITHUB_REF_SLUG_URL }}

          IMAGE_DIGEST_WEB=$(gcloud container images describe $IMAGE_TAG_WEB --format=json | jq -r '.image_summary.fully_qualified_digest')
          IMAGE_DIGEST_REACT=$(gcloud container images describe $IMAGE_TAG_REACT --format=json | jq -r '.image_summary.fully_qualified_digest')

          gcloud --project ${{ env.GCLOUD_PROJECT_DEV }} --quiet \
          beta run deploy template-ui-web \
          --platform=managed \
          --region=us-central1 \
          "--image=$IMAGE_DIGEST_WEB" \
          --allow-unauthenticated \
          --no-traffic \
          --tag pr-${{ github.event.number }} \
          --format=json > run_deploy_storybook_web.json

          gcloud --project ${{ env.GCLOUD_PROJECT_DEV }} --quiet \
          beta run deploy template-ui \
          --platform=managed \
          --region=us-central1 \
          "--image=$IMAGE_DIGEST_REACT" \
          --allow-unauthenticated \
          --no-traffic \
          --tag pr-${{ github.event.number }} \
          --format=json > run_deploy_storybook_react.json

      - name: Send comment
        uses: peter-evans/create-or-update-comment@v4
        if: github.event.action == 'opened'
        with:
          issue-number: ${{ github.event.number }}
          body: |-
            :fire: Here is the preview of the pull request:
            https://template-ui.croct.dev/pr-${{ github.event.number }}
