name: Preview deploy

on:
  push:
    branches:
      - master

env:
  GCLOUD_PROJECT_DEV: "croct-dev"

jobs:
  deploy-preview:
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rlespinasse/github-slug-action@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: "https://npm.pkg.github.com"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}

      - name: Install dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: npm ci

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "${{ secrets.GCLOUD_WORKLOAD_IDENTITY }}"
          service_account: "${{ secrets.GCLOUD_SERVICE_ACCOUNT }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Enable components
        run: |-
          gcloud auth configure-docker
          gcloud --quiet components install beta

      - name: Build & Publish
        run: |
          sed -i -e "s~http://localhost:6008~https://template-ui-web.croct.dev~" .storybook/react/main.ts
          npm run build-storybook -- --quiet --config-dir .storybook/web --output-dir storybook-static/web
          npm run build-storybook -- --quiet --config-dir .storybook/react --output-dir storybook-static/react

          docker build ./storybook-static/web \
          --file ./Dockerfile \
          --tag gcr.io/${{ env.GCLOUD_PROJECT_DEV }}/storybook-web \
          --push

          docker build ./storybook-static/react \
          --file ./Dockerfile \
          --tag gcr.io/${{ env.GCLOUD_PROJECT_DEV }}/storybook-react \
          --push

      - name: Deploy
        run: |-
          IMAGE_TAG_WEB=gcr.io/${{ env.GCLOUD_PROJECT_DEV }}/storybook-web
          IMAGE_TAG_REACT=gcr.io/${{ env.GCLOUD_PROJECT_DEV }}/storybook-react

          IMAGE_DIGEST_WEB=$(gcloud container images describe $IMAGE_TAG_WEB --format=json | jq -r '.image_summary.fully_qualified_digest')
          IMAGE_DIGEST_REACT=$(gcloud container images describe $IMAGE_TAG_REACT --format=json | jq -r '.image_summary.fully_qualified_digest')

          gcloud --project ${{ env.GCLOUD_PROJECT_DEV }} --quiet \
            beta run deploy template-ui-web \
            --platform=managed \
            --region=us-central1 \
            "--image=$IMAGE_DIGEST_WEB" \
            --allow-unauthenticated \
            --no-traffic \
            --tag master

          gcloud --project ${{ env.GCLOUD_PROJECT_DEV }} --quiet \
            beta run deploy template-ui \
            --platform=managed \
            --region=us-central1 \
            "--image=$IMAGE_DIGEST_REACT" \
            --allow-unauthenticated \
            --no-traffic \
            --tag master

          gcloud --project ${{ env.GCLOUD_PROJECT_DEV }} --quiet \
            beta run services update-traffic template-ui-web \
            --region=us-central1 \
            --to-tags=master=100 &

          gcloud --project ${{ env.GCLOUD_PROJECT_DEV }} --quiet \
            beta run services update-traffic template-ui \
            --region=us-central1 \
            --to-tags=master=100 &

          wait
