name: Send Storybook preview

on:
  pull_request:
    types:
      - opened
jobs:
  send-guidelines:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pullRequestOpened: |
            Here's the Storybook preview for this pull request:
            [https://{{ payload.base.ref }}--67c5fae036c2b363358e815b.chromatic.com](https://{{ payload.base.ref }}--67c5fae036c2b363358e815b.chromatic.com)
